#!/bin/bash
curl -X POST http://localhost:5001/create_user \
     -H "Content-Type: application/json" \
     -d '{"username": "johndoe", "email": "john@example.com", "password": "secure123"}'

sleep 5s

curl -X GET http://localhost:5001/get_user \
     -H "Content-Type: application/json" \
     -d '{"username": "johndoe"}'

